export { default as About } from "./About";
export * from "./Catalogue/Catalogue";
export * from "./CompanyDashboard";
export * from "./CompanyGames";
export * from "./CompanyLayout";
export * from "./CompanySales";
export * from "./EditGames";
export * from "./Home";
export * from "./Login";
export * from "./PublishGame";
export * from "./Register";
export * from "./ResetPassword";
export * from "./SpecificGame/SpecificGame";
